version: '3.8'

services:
  # ParkUp Backend Application
  parkup-backend:
    image: parkup-backend:latest
    container_name: parkup-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-shiny-lake-a8u29p55-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_RN7imPulM0Qg
      
      # JPA Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      
      # Server Configuration
      SERVER_PORT: 8080
      
      # Twilio Configuration (usar variables de entorno o secretos)
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-AC3cfb52237c1b121389d8e476db44e3f4}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-e0abdece91d32107c4061579656f0546}
      TWILIO_FROM_NUMBER: ${TWILIO_FROM_NUMBER:-+14155238886}
      
      # JWT Configuration
      AUTHORIZATION_JWT_SECRET: ${JWT_SECRET:-WriteHereYourSecretStringForTokenSigningCredentials}
      AUTHORIZATION_JWT_EXPIRATION_DAYS: ${JWT_EXPIRATION_DAYS:-7}
    depends_on:
      parkup-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - parkup-network

volumes:
  parkup-db-data:
    driver: local

networks:
  parkup-network:
    driver: bridge